Provide custom palette directly to neogit
scottmckendry/cyberdream.nvim pull request #153
Opened 2024-12-20 02:20 UTC by gldtn

Better integration with Neogit custom palette: https://github.com/NeogitOrg/neogit/blob/0820552997dd4dda4faa147228f0e61ea88290a3/doc/neogit.txt#L563

2024-12-20 03:13 UTC, scottmckendry requested changes

2024-12-20 03:13 UTC, scottmckendry commented on lua/cyberdream/extensions/neogit.lua
> +    local neogit = require("neogit")
We need to check if `neogit` can be loaded before we try to require it. If you don't have the plugin installed, it breaks cyberdream:

```
Failed to run `config` for cyberdream.nvim

vim/_editor.lua:0: /home/scott/git/nix/nvim/init.lua..nvim_exec2() called at /home/scott/git/nix/nvim/init.lua:0../home/scott/git/cyberdream.nvim/colors/cyberdream.lua: Vim(colorscheme):E5113: Error while calling lua chunk: ...git/cyberdream.nvim/lua/cyberdream/extensions/neogit.lua:8: module 'neogit' not found:
	no field package.preload['neogit']
```

```suggestion
    if not package.loaded["neogit"] then
        return {}
    end
    local neogit = require("neogit")
```

2024-12-20 18:54 UTC, scottmckendry commented
You could use Cattpuccin's implementation as a reference:

https://github.com/catppuccin/nvim/blob/f8a155ab5891c5d2fb709b7e85627f1783d5a5d9/lua/catppuccin/groups/integrations/neogit.lua

You probably won't need to define _all_ highlight groups; most default links should be fine to leave as is. 

They use `darken` & `lighten` helpers for darker and lighter colours for backgrounds etc. 

If you want to do something similar you can use `blend`. There's an example of this here:

https://github.com/scottmckendry/cyberdream.nvim/blob/731290012f435e06e4d5d64ed7c09cec49df2663/lua/cyberdream/extensions/markdown.lua

2024-12-21 07:21 UTC, gldtn commented
This removes `.setup()` call. Overall Neogit should look much cleaner with this update.

Question, when you set Cyberdream with `transparent = true`, does `fg` becomes white if set to `t.bg` on your terminal? Or is this a normal behavior in Neovim? I'm assuming Cyberdream sets `bg` to `"NONE"` if transparency is enabled.

For example:
`NeogitCommitViewHeader = { bg = t.cyan, fg = t.bg }`

To avoid this I set it to `t.bg_solid`

I noticed this behavior when customizing my fzf-lua/telescope, I can open a issue to show screenshots if necessary.

Thanks!

2024-12-22 05:09 UTC, merged

2024-12-22 05:09 UTC, scottmckendry commented
Great stuff @gldtn 🙂 thanks again for contributing to the project!