feat(colors, highlights): improved `NonText` readability
scottmckendry/cyberdream.nvim pull request #74
Opened 2024-06-14 22:46 UTC by AlejandroSuero

@scottmckendry a little tweak on the colours and the highlights to improve readability when using `NonText` and `NonText+CursorLine`. Usually used by AI plugins and terminal based plugins to show "ghost text".

> [!WARNING]
> Toggling light and dark 💥

- Before:

https://github.com/scottmckendry/cyberdream.nvim/assets/71392160/db0515f1-6054-449e-8bd8-a3374c18b8e4

Using `:term`:

https://github.com/scottmckendry/cyberdream.nvim/assets/71392160/4cdc091e-6cc2-41c6-b30c-8c9a60d1f20c

- After:

https://github.com/scottmckendry/cyberdream.nvim/assets/71392160/0d5aba57-1b0d-4bbb-883b-e1727859a412

Using `:term`:

<img width="756" alt="Screenshot 2024-06-15 at 00 16 14" src="https://github.com/scottmckendry/cyberdream.nvim/assets/71392160/8085dc29-15fe-4ed8-bc7f-46cf8e6d1cb2">

2024-06-14 22:51 UTC, AlejandroSuero commented
I force pushed cause I don't know how (87aee45) got in the PR while I was writing it 🤔

2024-06-14 23:22 UTC, scottmckendry commented
Wow @AlejandroSuero ! Appreciate all the work you're putting in on these PRs!

I think this is a very necessary change and should be fixed. However, I think we should try and make it work without affecting the base palette.  As you can probably already tell, this has the knock-on effect of updating _all_ of the extras that reference it.

You can use the `util.blend` function to produce new colors from the ones already available if there is nothing suitable in the palette itself.

2024-06-14 23:28 UTC, AlejandroSuero commented
@scottmckendry okay, I will play around to get a feel to mix the base palette.

2024-06-14 23:30 UTC, scottmckendry requested changes

2024-06-14 23:30 UTC, scottmckendry commented on lua/cyberdream/colors.lua
avoid updating the base palette if possible :)

2024-06-14 23:48 UTC, AlejandroSuero commented on lua/cyberdream/colors.lua
@scottmckendry I made the changes in (1eea635)

https://github.com/scottmckendry/cyberdream.nvim/assets/71392160/4da406e3-68be-4a8a-968d-55d32e950625

I made it so it differentiates from the `Comment` highlight so it doesn't conflict.

2024-06-15 00:17 UTC, scottmckendry requested changes
It's still showing lots of changes to extras, I think there still may be changes in `colors.lua` that differ from `main`. Can you check, please? Thanks!

2024-06-15 00:20 UTC, AlejandroSuero commented
@scottmckendry This has nothing to do with this PR but while I was playing around with the values, I used Telescope a lot and notice that there is no contrast between search and results and preview.

Here is my proposal.

- Without changing anything but `TelescopePrompt{Border,Normal,Prefix}`):

<img width="1504" alt="Changed with red theme" src="https://github.com/scottmckendry/cyberdream.nvim/assets/71392160/8d0eef2e-0179-4e32-a79f-f9ce767a2b4d">

- Changing the colours:

<img width="1504" alt="Changed with a blueish theme" src="https://github.com/scottmckendry/cyberdream.nvim/assets/71392160/f380cdb0-b710-4f0d-8c4f-7a1551f41ea7">

2024-06-15 00:21 UTC, AlejandroSuero commented
> It's still showing lots of changes to extras, I think there still may be changes in `colors.lua` that differ from `main`. Can you check, please? Thanks!

Okay I am going to copy the main branch colors.

2024-06-15 00:24 UTC, AlejandroSuero commented
@scottmckendry now it only changes 1 files, I check the colour contrast and still works correctly both in light and dark

2024-06-15 00:28 UTC, scottmckendry approved these changes

2024-06-15 00:29 UTC, merged

2024-06-15 00:53 UTC, scottmckendry commented
> @scottmckendry This has nothing to do with this PR but while I was playing around with the values, I used Telescope a lot and notice that there is no contrast between search and results and preview.
> 
> Here is my proposal.
> 
> * Without changing anything but `TelescopePrompt{Border,Normal,Prefix}`):
> 
> <img alt="Changed with red theme" width="1504" src="https://private-user-images.githubusercontent.com/71392160/339934846-8d0eef2e-0179-4e32-a79f-f9ce767a2b4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0MTMwMDksIm5iZiI6MTcxODQxMjcwOSwicGF0aCI6Ii83MTM5MjE2MC8zMzk5MzQ4NDYtOGQwZWVmMmUtMDE3OS00ZTMyLWE3OWYtZjljZTc2N2EyYjRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE1VDAwNTE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3M2Y2ZWIzN2JjMzdmN2MyYzg2Mjc2NDUxYzg5MTM2NzQ4ZjI5M2NkODE2ZWZhNDIwZDkyMmJmMGNiZjllN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fVVup25wBYkTY4FM4l0SX6ZjiBhmiUhdMaVyru_u9_A">
> * Changing the colours:
> 
> <img alt="Changed with a blueish theme" width="1504" src="https://private-user-images.githubusercontent.com/71392160/339935482-f380cdb0-b710-4f0d-8c4f-7a1551f41ea7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0MTMwMDksIm5iZiI6MTcxODQxMjcwOSwicGF0aCI6Ii83MTM5MjE2MC8zMzk5MzU0ODItZjM4MGNkYjAtYjcxMC00ZjBkLThjNGYtN2ExNTUxZjQxZWE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE1VDAwNTE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyOTVjMDliMDNjMTBjYTc1NzQzZjlhN2I3N2EwNjM5OWExOWYwNGI0NWJkNTExNjdhZGFhYTY1NDZlYWQ0OWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4QHBWyGXxzeR8bUG3mP-yY7MP0lyqWjlQDkpf1xfXyA">

@AlejandroSuero the blue looks quite nice. Do you have this change in a branch? Would like to see how it looks in person :)